INSERT INTO allergies (id, name) VALUES (1, 'Lactose');
INSERT INTO allergies (id, name) VALUES (2, 'Gluten');
INSERT INTO allergies (id, name) VALUES (3, 'Noten');
INSERT INTO recipes (id, book,page,kitchen,course,title,maxPreperationTime,persons,favorite,hide) VALUES (2, 'Smulweb', 5, 'Frans', 'Voorgerecht', 'Avocadobavarois en garnalentartaar als amuze of voorafje', 30, 4, 0, 0);
INSERT INTO ingredients (id, recipeID, name, amount, measure) VALUES (7, 2, 'Avocado', '2', '');
INSERT INTO ingredients (id, recipeID, name, amount, measure) VALUES (11, 2, 'Gekookte garnalen', '6', 'garnalen');
INSERT INTO ingredients (id, recipeID, name, amount, measure) VALUES (10, 2, 'Room', '120', 'gr');
INSERT INTO ingredients (id, recipeID, name, amount, measure) VALUES (8, 2, 'Sap van citroen', '1', 'citroen');
INSERT INTO ingredients (id, recipeID, name, amount, measure) VALUES (9, 2, 'Tabasco', '', '');
INSERT INTO ingredients (id, recipeID, name, amount, measure) VALUES (12, 2, 'Zalmeitjes', '', '');
INSERT INTO allergiesrecipes (recipeId, allergyId) VALUES (2, 1);